### ISSUE TITLE
PHP-FPM access/slow logs have disappeared

### ISSUE THREAD

**Issue by zerodeux** [factorysh/docker-php#12]
The only output I seem to get with 'docker logs <php_container>' is the php-fpm manager (PID 1) which uses stderr. What I see from such a broken container : 

```
# docker exec -ti -u root app_php_1 bash

root@eccf1ecb0c50:/# egrep 'log.*(access|slow|error)' /etc/php/7.0/fpm/pool.d/www.conf 
; The log file for slow requests
; Note: slowlog is mandatory if request_slowlog_timeout is set
slowlog = /var/log/php/.slow.log
;php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/php/.error.log
php_admin_flag[log_errors] = on

root@eccf1ecb0c50:/# ls -la /var/log/php/
total 8
drwxr-xr-x 2 root root 4096 Oct 17 16:36 .
drwxr-xr-x 1 root root 4096 Oct 17 16:36 ..
lrwxrwxrwx 1 root root   12 Oct 17 16:36 .access.log -> /proc/1/fd/1
lrwxrwxrwx 1 root root   12 Oct 17 16:36 php7.0-fpm.log -> /proc/1/fd/2
lrwxrwxrwx 1 root root   12 Oct 17 16:36 www.access.log -> /proc/1/fd/1
lrwxrwxrwx 1 root root   12 Oct 17 16:36 www.error.log -> /proc/1/fd/2
lrwxrwxrwx 1 root root   12 Oct 17 16:36 www.slow.log -> /proc/1/fd/2
```

I can reproduce the pb with this minimal example (app works, but no access log thru 'docker logs'): 
```
FROM bearstech/php:7.0

RUN useradd www

COPY src/wordpress /var/www

USER www
```

PS: also could we stop the indirect magic with symlinks and just plainly configure things such as "access.log = /proc/1/fd/1" ?

**Comment by zerodeux** [comment]
I live-patched a container with "access.log=/proc/1/fd/2" (+ "kill -USR2 1" for fpm reload) and it works, the access log output is available via "docker logs <php_container>".

**Comment by athoune** [comment]
PR https://github.com/factorysh/docker-php/pull/11 merged.

With complete path, you can use a volume for a specific log.
