### ISSUE TITLE
FPM's slow and error logs are munged

### ISSUE THREAD

**Issue by zerodeux** [factorysh/docker-php#15]
Shell-like variables in conf/www.conf are interpolated by the entrypoint, but it clashes with FPM own's internal shell-like interpolation at runtime. The "$pool" are substituted with a null string by entrypoint.sh and the container's www pool conf ends up with :

```
access.log = /var/log/php/.access.log
slowlog = /var/log/php/.slow.log
php_admin_value[error_log] = /var/log/php/.error.log
```

Which obviously does not work. I suggest to replace $pool by "www" in conf/www.conf since I don't think it makes sense to mange two FPM pools  in one container.

PS: there's a "/var/log/php/.access.log" symlink in the Dockerfile, I guess the problem was partially identified, and it does not feel like the right approach anyway. I also suggest to remove this strangely hidden symlink.

**Comment by maurice-audin** [comment]
@zitune Fixed as asked by @zerodeux, also updated some shaXXX sums. "make build" is ok, you can test and push to registry.

**Comment by maurice-audin** [comment]
Pushed on docker hub.
