### ISSUE TITLE
PHP-FPM remote address is not properly shown in its access.log

### ISSUE THREAD

**Issue by zerodeux** [factorysh/docker-php#16]
Current conf in /etc/php/7.0/fpm/pool.d/www.conf uses %{X-FORWARDED-FOR}e to display the remote address, but on my production containers it shows a '-'.

Testing with phpinfo(), I checked that in common situations (traversing AWS ELB ou HAproxy, then a bearstech/nginx-based container) :

* 1. The original IP client is correctly transmitted to $_SERVER[REMOTE_ADDR]
* 2. The X-Forwarded-For header does not seem to be transmitted to PHP

Since I think PHP does not have to care and fiddle with X-Forwarded-For (and eg. Wordpress is notoriously bad at it), point 2 looks fine to me.

In order to use 1, it can be fixed by replacing %{X-FORWARDED-FOR}e with %{REMOTE_ADDR}e in /etc/php/7.0/fpm/pool.d/www.conf 'access.format' directive. Tested with a live patch in one of my containers, works for me.

**Comment by maurice-audin** [comment]
Fixed and pushed to registry
